import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),target=path.join(root,'events-data.json');
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const date=s=>s?.match(/20\d\d[.\/-]\d\d[.\/-]\d\d/)?.[0].replace(/[.\/]/g,'-')||null;
const url=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}};
const get=async(u,body)=>{const r=await fetch(u,{signal:AbortSignal.timeout(20000),...(body?{method:'POST',body:new URLSearchParams(body)}:{})});if(!r.ok)throw Error('HTTP '+r.status);return r.text();};
const delay=()=>new Promise(r=>setTimeout(r,400));
export function mergeManualEvents(events,manual,today,end){
 if(!Array.isArray(manual))throw Error('수동 행사 자료 형식 오류');
 const items=manual.filter(e=>{if(!e||typeof e.id!=='string'||!e.id.startsWith('concert_manual_')||e.kind!=='concert'||!e.title||!date(e.startDate)||!date(e.endDate)||!url(e.sourceUrl)||!url(e.bookingUrl)||!Array.isArray(e.sales)||e.sales.some(s=>!Number.isFinite(Date.parse(s.at))||!url(s.sourceUrl)))throw Error('수동 행사 검증 실패');return e.endDate>=today&&e.startDate<=end;});
 return [...new Map([...events.filter(e=>!e.manual),...items].map(e=>[e.id,e])).values()];
}
async function collectEvents(){const now=new Date(),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(now),until=new Date(today+'T00:00:00Z');until.setUTCFullYear(until.getUTCFullYear()+1);const end=until.toISOString().slice(0,10),events=[],sources=[];
let old;try{old=JSON.parse(await fs.readFile(target,'utf8'))}catch{old={events:[],sources:[]}}
const collect=async(kind,fn)=>{try{const items=await fn();if(!items.length)throw Error('수집 결과가 비어 있어 이전 자료를 유지합니다.');events.push(...items);sources.push({kind,checkedAt:now.toISOString(),ok:!items.failures,partialFailures:items.failures||0,count:items.length});console.log(kind,items.length)}catch(e){events.push(...old.events.filter(x=>x.kind===kind));sources.push({kind,checkedAt:old.sources.find(x=>x.kind===kind)?.checkedAt||null,attemptedAt:now.toISOString(),ok:false,error:e.message});console.log(kind,'FAILED',e.message)}};
await collect('festival',async()=>{const found=new Map();for(const searchDate of ['A','B'])for(let startIdx=0;startIdx<3000;){const j=JSON.parse(await get('https://korean.visitkorea.or.kr/kfes/list/selectWntyFstvlList.do',{startIdx:String(startIdx),searchType:'A',searchDate,searchArea:'',searchCate:'',filterExcluded:'true'}));if(!Array.isArray(j.resultList))throw Error('축제 응답 형식 변경');for(const p of j.resultList){const start=date(p.fstvlBgngDe),finish=date(p.fstvlEndDe);if(!start||!finish||finish<today||start>end)continue;const sourceUrl='https://korean.visitkorea.or.kr/kfes/detail/fstvlDetail.do?fstvlCntntsId='+p.fstvlCntntsId;const official=p.fstvlHmpgUrl?.match(/href=["']([^"']+)/)?.[1];found.set(p.fstvlCntntsId,{id:'festival_'+p.fstvlCntntsId,kind:'festival',title:clean(p.cntntsNm),startDate:start,endDate:finish,venue:clean(p.dtadr||p.areaNm),region:clean(p.areaNm),address:clean(p.adres),sourceUrl,sourceName:'한국관광공사',bookingUrl:url(official),bookingLabel:'공식 홈페이지·예약 안내',sales:[],checkedAt:now.toISOString()});}startIdx+=j.resultList.length;if(!j.resultList.length||startIdx>=Number(j.totalCnt))break;await delay();}return [...found.values()]});
await collect('concert',async()=>{const found=new Map();for(let page=1;page<=100;page++){const html=await get('https://ticket.yes24.com/New/Genre/Ajax/GenreList_Data.aspx?'+new URLSearchParams({genre:'15456',sort:'0',area:'',genretype:'1',pCurPage:String(page),pPageSize:'20'}));let count=0;for(const m of html.matchAll(/<a\b[^>]*onclick=['"]jsf_base_GoToPerfDetail\((\d+)\);['"][^>]*>([\s\S]*?)<\/a>/g)){count++;const ps=[...m[2].matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].map(x=>clean(x[1]));const dates=ps[1]?.match(/20\d\d\.\d\d\.\d\d/g)||[],start=date(dates[0]),finish=date(dates[1]||dates[0]);if(!start||finish<today||start>end)continue;const sourceUrl='https://ticket.yes24.com/Perf/'+m[1];found.set(m[1],{id:'concert_'+m[1],kind:'concert',title:ps[0],startDate:start,endDate:finish,venue:ps[2]||'',region:'',sourceUrl,sourceName:'YES24 티켓',bookingUrl:sourceUrl,bookingLabel:'YES24 예매',sales:[],checkedAt:now.toISOString()});}const total=Number(html.match(/id="ListTotalCnt" value="(\d+)"/)?.[1]);if(!count)throw Error('공연 목록 형식 변경');if(page*20>=total)break;await delay();}
// Exact dates are read only from the ticket-opening column. No guessed opening times.
const key=s=>s.replace(/티켓 오픈 안내|단독판매|선예매|[^가-힣a-z0-9]/gi,'').toLowerCase();
for(let page=1;page<=8;page++){const html=await get('https://ticket.yes24.com/New/Notice/Ajax/axList.aspx',{page:String(page),size:'20',genre:'15456',province:'',order:'',searchType:'All',searchText:''});for(const m of html.matchAll(/<tr>([\s\S]*?)<\/tr>/g)){const cells=[...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map(x=>x[1]);if(cells.length<3)continue;const title=clean(cells[1]),id=cells[1].match(/#id=(\d+)/)?.[1],stamp=clean(cells[2]).match(/(20\d\d\.\d\d\.\d\d)\([^)]*\)\s*(\d\d:\d\d)/);if(!stamp||!id)continue;const sourceUrl='https://ticket.yes24.com/New/Notice/NoticeMain.aspx#id='+id;let e=[...found.values()].find(e=>key(e.title)===key(title));if(!e){e={id:'concert_notice_'+id,kind:'concert',title:title.replace(/티켓 오픈 안내$/,'').trim(),startDate:null,endDate:null,venue:'공연일·장소는 예매 공지 확인',region:'',sourceUrl,sourceName:'YES24 티켓오픈 공지',bookingUrl:sourceUrl,bookingLabel:'예매 공지·접수 링크',sales:[],checkedAt:now.toISOString()};if(date(stamp[1])<today)continue;found.set('notice'+id,e);}e.sales.push({label:'일반예매',at:date(stamp[1])+'T'+stamp[2]+':00+09:00',sourceUrl});for(const n of [1,2]){const time=cells[2].match(new RegExp('presaleTime'+n+"=['\"]([^'\"]+)"))?.[1],label=cells[2].match(new RegExp('presaleTit'+n+"=['\"]([^'\"]+)"))?.[1];const mt=time?.match(/(20\d\d\.\d\d\.\d\d)\([^)]*\)\s*(\d\d:\d\d)/);if(mt)e.sales.push({label:label||'선예매',at:date(mt[1])+'T'+mt[2]+':00+09:00',sourceUrl});}}await delay();}return [...found.values()]});
await collect('marathon',async()=>{const links=new Set();for(let i=0;i<=12;i++){const d=new Date(today+'T00:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+i);const month=d.toISOString().slice(0,7);let html;try{html=await get('https://runningon.co.kr/marathon/'+month)}catch(e){if(e.message==='HTTP 404')continue;throw e;}for(const m of html.matchAll(/href="(\/races\/[a-z0-9-]+)"/g))links.add('https://runningon.co.kr'+m[1]);await delay();}const items=[];let failures=0;for(const link of links){try{const html=await get(link);const docs=[...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].flatMap(m=>JSON.parse(m[1]));const p=docs.find(x=>x['@type']==='SportsEvent');if(!p)throw Error('대회 형식 변경');const start=date(p.startDate),finish=date(p.endDate||p.startDate);if(!start||finish<today||start>end)continue;const offer=Array.isArray(p.offers)?p.offers[0]:p.offers;const at=offer?.validFrom;items.push({id:'marathon_'+link.split('/').at(-1),kind:'marathon',title:clean(p.name),startDate:start,endDate:finish,venue:clean(p.location?.name),region:clean(p.location?.address?.addressRegion),address:clean(p.location?.address?.streetAddress),sourceUrl:link,sourceName:'러닝온 공개 일정',officialUrl:url(p.organizer?.url),bookingUrl:url(offer?.url||p.organizer?.url),bookingLabel:'주최 측 참가 신청',registrationDate:date(at),registrationStatus:offer?.availability?.split('/').at(-1)||'',sales:/T\d\d:\d\d/.test(at||'')?[{label:'참가 접수',at,sourceUrl:link}]:[],checkedAt:now.toISOString()});}catch{failures++}await delay();}if(failures)console.log('마라톤 상세 실패',failures);if(failures){const ids=new Set(items.map(x=>x.id));items.push(...old.events.filter(x=>x.kind==='marathon'&&!ids.has(x.id)));}items.failures=failures;return items});
let manual=[];try{manual=JSON.parse(await fs.readFile(path.join(root,'manual-events.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
const unique=mergeManualEvents(events,manual,today,end).sort((a,b)=>(a.startDate||'9999').localeCompare(b.startDate||'9999'));const data={version:1,updatedAt:now.toISOString(),window:{from:today,to:end},sources,events:unique};await fs.writeFile(target+'.tmp',JSON.stringify(data,null,2));await fs.rename(target+'.tmp',target);return data;}
export async function refreshEvents(){const lock=target+'.lock';let handle;try{handle=await fs.open(lock,'wx')}catch(e){if(e.code==='EEXIST')throw Error('다른 행사 갱신이 진행 중입니다.');throw e;}try{return await collectEvents()}finally{await handle.close();await fs.unlink(lock).catch(()=>{});}}
if(process.argv[1]===fileURLToPath(import.meta.url))await refreshEvents();
